### ISSUE TITLE
Commit modified files on behalf of SCM Provider

### ISSUE THREAD

**Issue by dtretyakov** [rugpanov/teamcity-vscode-extension#6]
After the running personal build we need to commit modified files.

**Comment by rugpanov** [comment]
We need SCM Provider APIs from either tfvc and git to commit modified files.
- [ implement git api ] 
- [ implement tfvc api ]

**Comment by rugpanov** [comment]
Implemented for Tfs.
User can commit with git, but currently can't push it.
